### ISSUE TITLE
Add support for iOS App Extensions

### ISSUE THREAD

**Issue by kattrali** [bugsnag/bugsnag-cocoa#100]
Bugsnag v5.0.x is incompatible with iOS App Extension requirements due to a reference to `[UIApplication sharedApplication]` within [`KSCrashReportSinkEMail.m`](https://github.com/kstenerud/KSCrash/blob/master/Source/KSCrash/Reporting/Sinks/KSCrashReportSinkEMail.m#L140) (unused within Bugsnag).

**Comment by SSheldon** [comment]
At least for CocoaPods, it looks like this can be fixed by removing the `KSCrash/Reporting` dependency, though I think that'll have to wait until after kstenerud/KSCrash#127. With that PR, the header file defining the `KSCrashReportFilter` protocol is made public in `KSCrash/Recording` to fix a compiler issue, and I assume that issue is the whole reason the `KSCrash/Reporting` dependency was added :smile:

**Comment by kattrali** [comment]
Your assumption is correct, @SSheldon :smile: - Just hadn't gotten back around to sorting out subspecs to get a working build without `Reporting`

**Comment by kattrali** [comment]
Fixed in 36de94c - Released as [5.1.0](https://github.com/bugsnag/bugsnag-cocoa/blob/master/CHANGELOG.md#510)
