### ISSUE TITLE
Handle error sends data even with incorrect API Key

### ISSUE THREAD

**Issue by prgorasiya** [bugsnag/bugsnag-cocoa#1003]
There are actually 2 issues I am reporting
1st:
SDK sends handled error logs even when the API key is incorrect.(Not sure if its intended and same with crash logs)

2nd:
Error log size is huge when number of handled errors increase. Hence consumes lot of bandwidth.
Kindly refer to this screenshot, its when SDK is uploading the logs and if the number of errors are more then its also reaching up to 1GB.

<img width="1790" alt="Screen Shot 2021-02-14 at 9 30 02 AM" src="https://user-images.githubusercontent.com/11789986/108012216-ce3a9e80-7043-11eb-82b9-1e794d49f7f1.png">

### Steps to reproduce
1. Run this code using repeating Timer with interval of say 5 seconds and let it run for a couple of minutes
```
let error = NSError(domain: "Handled error name", code: 0, userInfo: nil)
Bugsnag.notifyError(error) { event in
     event.addMetadata(data, key: "<error data>", section: "NSERROR")
     event.severity = .error
     return true
}
```
2. Relaunch the app so the SDK could upload generated logs, if they were not uploaded in the first launch
3. Check the bandwidth consumed by API `notify.bugsnag.com` using charles proxy software or any other similar APP

### Environment
* Bugsnag version: 6.6.2
* Carthage version (if any):0.37.0
* iOS/tvOS/macOS version(s): iOS 14.4
* Simulator or physical device: Physical device
* Xcode version: 12.4
* Swift version (if applicable): 5.3

**Comment by xander-jones** [comment]
👋 . hey @prgorasiya 

> SDK sends handled error logs even when the API key is incorrect.(Not sure if its intended and same with crash logs)

This is expected behaviour for an API key that is non-null. We only raise an error if the API key is `nil`, or an empty string. If an API Key exists, but is invalid you'll see a warning:

```
[Bugsnag] [WARN] Attempted to set an invalid Event API key
```

> Error log size is huge when number of handled errors increase. Hence consumes lot of bandwidth.

By default, we persist a maximum or 32 events to device before we start to overwrite them, but you can modify this value in configuration though: https://docs.bugsnag.com/platforms/ios/configuration-options/#maxpersistedevents

If I disable network connectivity of the application, and send 50 events using your snippet above, only the latest 32 are persisted to memory. If I then close the application, restore network connectivity and relaunch, it sends the latest 32 events only (which used ~1.4MB in total, ~44KB per report).

The only difference here is that I had to modify `data` to just be a string `"data"`, what are you setting as `data` here in your use case?

I am not sure where you're seeing the 1GB+ value in your screenshot, can you please clarify what you mean here? Please note any payloads over 1MB are rejected by the Bugsnag servers.

**Comment by prgorasiya** [comment]
@xander-jones Is there a way to disable sending logs if the key is invalid, without causing Mobile apps to crash or face issue because of that?

I just used this data while testing `["error" : "<error name>", "code" : <Int value>]`
How can I check what information the SDK is sending for handled errors?

I understand that without specifying it persist max events and I think that could be the reason behind cumulative bandwidth consumption of 1GB+ by our App in a period of a couple of days and majority of it was due to uploading many events.

What would happen if I were to set max persist events to 1?
How would persisted events be uploaded and replaced by new events?

**Comment by xander-jones** [comment]
> Is there a way to disable sending logs if the key is invalid

These warning logs are local, not sent to Bugsnag, sorry if that was not previously clear. Why would you want to set an invalid API key? It sounds like you may want to check out customizing reports through callbacks to reject them this way rather than using an invalid key? https://docs.bugsnag.com/platforms/ios/customizing-error-reports/#discarding-events If not, can you let us know what you're looking to achieve and we may be able to offer a better solution.

> How can I check what information the SDK is sending for handled errors?

You can use something like an HTTP proxy to monitor requests being sent back and forth, or alternatively use a dummy interface and [configure your endpoints](https://docs.bugsnag.com/platforms/ios/configuration-options/#endpoints) in Bugsnag to match this request catcher (e.g. https://requestcatcher.com/)

> What would happen if I were to set max persist events to 1?

The event store acts like a ring buffer. By setting the max persisted events to 1, any event stored will always be overwritten if it's not sent off in time, and this depends on the network connection of the device. It can take anywhere from a few milliseconds up to a few seconds.

> How would persisted events be uploaded and replaced by new events?

When an event is sent to Bugsnag, it's removed from the ring buffer, and therefore removed from device memory. Under normal operating conditions with a nominal network connection, the queue shouldn't be backing up to more than 32 events unless you are hammering events to Bugsnag in quick succession, in which case the queue acts as a buffer to stop a _huge_ amount of bandwidth being used on your users' devices.

Bandwidth consumption-wise, if you send 1000 events at 1MB/each, this will incur ~1GB of bandwidth use, there's nothing we can do to avoid this, regardless of how large the `maxPersistedEvents` value is. The snippet above produces events of around 44KB though, so you'd need to send 24,000+ events to hit 1GB of bandwidth. I'm not sure where the 1GB figure is seen though, I can only see an outgoing request size of 1.42MB, can you please clarify?

**Comment by prgorasiya** [comment]
1GB figure is received from our live users, not during testing. However I could also reach to that number if I keep on sending error for a while if I keep persist value to max, but thats not a problem now.

Is there a way to reduce the amount of information being sent in each error log?
I would prefer to only send error data and exclude breadcrumbs to reduce the size of json file.

**Comment by xander-jones** [comment]
Yes absolutely, you may want to consider the following options to reduce the amount of data being sent:
* `sendThreads`: https://docs.bugsnag.com/platforms/ios/configuration-options/#sendthreads you may want to select to only send threads for unhandled errors, not for your handled calls to `Bugsnag.notify()` which reduces the data bandwidth required, but still gets you vital information for unhandled crashes.
* `enabledBreadcrumbTypes`: https://docs.bugsnag.com/platforms/ios/configuration-options/#enabledbreadcrumbtypes you may want to select only some of none of the automatically collected breadcrumbs. By turning this auto breadcrumbs off, you can still add manual ones which you of course have control over the number you're adding!
* `maxBreadcrumbs`: https://docs.bugsnag.com/platforms/ios/configuration-options/#maxbreadcrumbs reduce the total number of breadcrumbs to a level you're happy with, set it to zero if you don't want any!

Closing the issue out as I don't believe there's any bug here, but do let us know if you've got any other queries.
