### ISSUE TITLE
Crash in release build mode

### ISSUE THREAD

**Issue by Rusik** [bugsnag/bugsnag-cocoa#108]
Crash when trying to send excepton with `+ (void)notify:(NSException *_Nonnull)exception withData:(NSDictionary *_Nullable)metaData atSeverity:(NSString *_Nullable)severity`. Updating KSCrash to 1.6 fix this problem.

**Comment by kattrali** [comment]
Hi @Rusik, thank you for the report. Can you tell me a few details about this exception to ensure that updating the dependency version is the root cause:

* Which versions of Bugsnag and KSCrash you were using before the crash occurred (or make a gist of your `Cartfile.resolved` or `Podfile.lock`)?
* What was the description and class of the exception?

**Comment by kattrali** [comment]
Fixed in v5.3.0
