### ISSUE TITLE
App Hang detected when adding metadata values to Bugsnag client

### ISSUE THREAD

**Issue by rebello95** [bugsnag/bugsnag-cocoa#1086]
### Describe the bug
Since updating the SDK and consuming the new "app hang" detection functionality, we have begun to see some crashes that seem to be coming from app hangs triggered when writing metadata attributes to the Bugsnag SDK itself:

<img width="922" alt="Screen Shot 2021-04-28 at 4 04 42 PM" src="https://user-images.githubusercontent.com/2643476/116483239-9027db00-a83b-11eb-8c6e-9e5828807b84.png">

### Steps to reproduce
Although we have not been able to reproduce manually, the general expected steps are:
1. Launch the app and start Bugsnag
2. Repeatedly write a large amount of attributes to the Bugsnag metadata using `addMetadata` (which eventually calls through to [this codepath](https://github.com/bugsnag/bugsnag-cocoa/blob/981cc251cc8006b1291533258293e3431d620ae1/Bugsnag/Client/BugsnagClient.m#L989))

### Environment
* Bugsnag version: 6.8.3
* CocoaPods version:
* Carthage version (if any):
* iOS/tvOS/macOS version(s):
* Simulator or physical device: Physical device
* Xcode version: 12.4
* Swift version (if applicable): Swift 5.4

### Additional info

It looks like Bugsnag is using `@synchronized` when [writing the underlying JSON file](https://github.com/bugsnag/bugsnag-cocoa/blob/981cc251cc8006b1291533258293e3431d620ae1/Bugsnag/Client/BugsnagClient.m#L989). Would it make sense to move this to a background thread internally?

**Comment by rebello95** [comment]
cc @sberrevoets @Augustyniak

**Comment by xander-jones** [comment]
Hey @rebello95 & team 👋 . By design, our library writes metadata on the calling thread as you noted: this is to guarantee updates to metadata aren't lost if the app crashes immediately afterwards. So the main thread would be used in this case, if metadata is being added just after initialization of Bugsnag. I have raised this internally to discuss whether documentation or product changes could be made to improve things.

There's a few things that can be done to help improve this in the meantime, especially if addition of metadata is a heavy operation on start:

* Add metadata to the configuration object before initializing Bugsnag (https://docs.bugsnag.com/platforms/ios/configuration-options/#addmetadata) – but I appreciate that all of the required metadata may not be available at Bugsnag initialization time.
* Use a single call to `addMetadata(_:section:)` instead of multiple calls to `addMetadata(_:key:section:)`, or at least reduce the number of calls to a minimum to reduce writes to disk on the calling thread.
* Move this operation to a background job with a `DispatchQueue`. As noted above, this means the metadata is not guaranteed to be written to disk by the time an error may occur. However you may decide that this is a reasonable trade-off for your use case, or for some metadata at least.

**Comment by rebello95** [comment]
Thanks for the reply @xander-jones!

> our library writes metadata on the calling thread as you noted: this is to guarantee updates to metadata aren't lost if the app crashes immediately afterwards. So the main thread would be used in this case, if metadata is being added just after initialization of Bugsnag.

This reasoning makes sense to me.

> Add metadata to the configuration object before initializing Bugsnag

As you alluded to, this would be ideal but unfortunately our app is split out into various different components that register themselves to provide additional metadata to the crash reporting service (Bugsnag), and these values change quite often over time. Specifically, we are reporting new feature flags that are accessed during app launch as each one is accessed, and this happens in rapid succession which results in all the writes within Bugsnag.

> Use a single call to addMetadata(_:section:) instead of multiple calls to addMetadata(_:key:section:), or at least reduce the number of calls to a minimum to reduce writes to disk on the calling thread.

This is possible, but similar to your last point about `DispatchQueue` usage, it could result in losing some valuable metadata if the app were to crash while some buffered metadata is pending being passed to the Bugsnag SDK. What are your thoughts on adding a mechanism within Bugsnag to do something like this:
- Buffer new metadata and rate-limit the amount of disk writes happening (i.e., only once every 0.5s)
- Write to disk at most as often as the rate-limit, and hold all new/pending metadata in memory until the next possible write
- (I'm not sure if this is possible, but just throwing the idea out there): In the event of an exception, attempt to do an immediate disk write with any pending values regardless of rate-limit
- This could potentially be configured at SDK startup time

My thinking with something like this is that it would allow external callers to pass new metadata to the SDK while allowing it to write that data as often as possible while still maintaining efficiency and data integrity in the event of a crash.

**Comment by mattdyoung** [comment]
Hi @rebello95 

Thanks for your detailed thoughts on this. We're currently investigating options, some of them along the lines of your suggestions, to identify how we should improve performance in this area.

We'll report back on this issue when we release any improvements. Thanks!

**Comment by rebello95** [comment]
Sounds great, thank you!

**Comment by luke-belton** [comment]
Hi @rebello95, just to let you know we've released https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.10.0 of `bugsnag-cocoa` which contains performance improvements, including [when adding metadata](https://github.com/bugsnag/bugsnag-cocoa/pull/1133) which should reduce instances of any App Hangs such as the one you saw in this issue.

**Comment by rebello95** [comment]
Thanks so much, @luke-belton! We've upgraded and will hopefully see those improvements in our app when we roll out 🙏🏽
