### ISSUE TITLE
Expose `depth` param for Bugsnag.notify() method

### ISSUE THREAD

**Issue by andyvb** [bugsnag/bugsnag-cocoa#109]
In our Swift project, we have an `enum` for typical errors that are handled by our app, and we create a new `NSException` for each `enum`. We have all this logic wrapped in a helper method. Unfortunately, we can't use a single helper method when we call Bugsnag, since the stack trace includes the helper method path. 

It seems the workaround for this would be to create our own wrapper method around `Bugsnag.notify()`, but we need pass in our own value of the `depth` parameter to avoid Bugsnag reporting the helper method as the root of the stack trace. Unfortunately adding our own method override to `Bugsnag.notify()` doesn't work since `BugsnagNotifier` is not exposed (we use CocoaPods).

There are a couple ways I can think of to work around this:
A. Expose a new method that allows the `depth` parameter to be passed in, e.g:
```objectivec
@interface Bugsnag
+ (void)notify:(NSException *_Nonnull)exception
      withData:(NSDictionary *_Nullable)metaData
    atSeverity:(NSString *_Nullable)severity
       atDepth:(NSUInteger)depth  // <--- add this
...
```
B. Expose `BugsnagNotifier` publicly in the Podspec, so I can extend Bugsnag.m to accept a depth parameter. Trivially, the implementation of this method would look like this:

```objectivec
@interface Bugsnag ()
+ (BugsnagNotifier*)notifier;
@end

@implementation Bugsnag (Helpers)
+ (void)notify:(NSException *_Nonnull)exception
      withData:(NSDictionary *_Nullable)metaData
    atSeverity:(NSString *_Nullable)severity
       atDepth:(NSUInteger) depth
{
    [self.notifier notify:exception
                 withData:metaData
               atSeverity:severity
                  atDepth:depth];
}
```

**Comment by kattrali** [comment]
Hi @andyvb, thank you for the report. I'm currently working on a refactor which will expose this and other properties of the error report via block instead of adding more parameters to `notify:` ad nauseum. The relevant progress is on [this branch](https://github.com/bugsnag/bugsnag-cocoa/blob/kattrali/make-error-reports-editable/Source/Bugsnag.h#L85) and will be in the next minor release. 

As a part of this change, `depth` and several other properties will be editable via the [`BugsnagCrashReport` class](https://github.com/bugsnag/bugsnag-cocoa/blob/kattrali/make-error-reports-editable/Source/BugsnagCrashReport.h#L126).

**Comment by andyvb** [comment]
That's great news, thanks @kattrali!

**Comment by philihp** [comment]
If you're changing your public interface with breaking changes, could you increment your major version number?

**Comment by kattrali** [comment]
Hi @philihp, there were no breaking changes for this release, as the existing methods still work but were deprecated.
