### ISSUE TITLE
Upload prebuilt binaries for current and future releases

### ISSUE THREAD

**Issue by ranunez** [bugsnag/bugsnag-cocoa#120]
Prebuilt binaries of the framework can be uploaded to a release. When building using Carthage, it will automatically use this prebuilt framework instead of building completely from scratch, significantly decreasing integration time for users.

https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

**Comment by kattrali** [comment]
Thank you for the suggestion, @ranunez. 

While convenient, prebuilt binaries can also lead to confusion since frameworks which run in both the simulator and on devices (“fat” or “universal” frameworks) are not accepted in the app store and require additional steps to strip before uploading for review. If the frameworks are not universal, then many users would be confused when downloading and using the frameworks, since they would only work in the simulator or on a ARMv7 device or on an ARM64 device. 

For this reason, the recommended process is to compile from source, as the correct platform will be targeted automatically and reduce confusion, even if there are additional steps up front. This may be something to be revisited at a later date, but this is the recommendation for now.
