### ISSUE TITLE
Support for `preconditionFailure` message

### ISSUE THREAD

**Issue by mattyohe** [bugsnag/bugsnag-cocoa#132]
Calls to Swift's `preconditionFailure` (and likely its friends `assertionFailure`, `fatalError` etc) that occur in 5.6.5 do not appear to bubble up the message parameter for reporting in the stack trace that is viewable on Bugsnag.com.

It is unclear to me if this is a deficiency in Bugsnag or Swift.

Example:
Calling the code below in an application that uses Bugsnag:
```swift
public var name: String {
  preconditionFailure("Example of an error")
}
```
Would produce a trace similar to:
```
0  MyApp               name.get (MyApp.swift:10:20)
```

But the message `"Example of an error"` would not be reported.

**Comment by kattrali** [comment]
Interesting. Thanks for the report, @mattyohe. I'll look into it :female_detective:

**Comment by kattrali** [comment]
It looks like there's no message because the provided text isn't attached to the exception in some way, and is only printed. [`preconditionFailure`](https://github.com/apple/swift/blob/adc54c8a4d13fbebfeb68244bac401ef2528d6d0/stdlib/public/core/Assert.swift#L164), [`fatalError`](https://github.com/apple/swift/blob/adc54c8a4d13fbebfeb68244bac401ef2528d6d0/stdlib/public/core/Assert.swift#L187), et cetera call [`_assertionFailure`](https://github.com/apple/swift/blob/adc54c8a4d13fbebfeb68244bac401ef2528d6d0/stdlib/public/core/AssertCommon.swift#L83), which prints the message using [`_swift_stdlib_reportFatalErrorInFile`](https://github.com/apple/swift/blob/adc54c8a4d13fbebfeb68244bac401ef2528d6d0/stdlib/public/stubs/Assert.cpp#L52) before terminating execution using `Builtin.int_trap()`.

For now, I don't see how we can support this, but its something to revisit in the future and potentially discuss on the mailing list, as I think we can make the function arguments more accessible.

**Comment by edenman** [comment]
Is there a different method we should call instead of `fatalError` to get the message to propagate on a forced crash?

**Comment by edenman** [comment]
Also FWIW the Sentry guys seem to have figured out how to extract the message: https://github.com/getsentry/sentry-cocoa/pull/188/files
