### ISSUE TITLE
Wired stack trace: "...ContiguousArrayBuffer._checkValidSubscript..."

### ISSUE THREAD

**Issue by yaronlevi** [bugsnag/bugsnag-cocoa#137]
I have a React Native project and using bugsnag-react-native@2.0.2, but I think it's related to the native side.

Inside a **React Native swift module** I have this code to intentionally cause an exception:

<img width="737" alt="screen shot 2017-03-10 at 17 26 19" src="https://cloud.githubusercontent.com/assets/5398977/23800887/ba0329d8-05b6-11e7-8e96-0410d67cd8c4.png">

These lines of code simply access an array's index which is out of range.

The error is being reported to Bugsnag and I can see it in the dashboard but the stack trace has nothing to do with lines of code that causes the error or some kind of a hint to where I can find them. Instead, I get this error title:

**generic specialization <Swift.Int> of Swift._ContiguousArrayBuffer._checkValidSubscript (Swift.Int) -> ()**

Here is screen capture:

<img width="1046" alt="screen shot 2017-03-10 at 17 30 29" src="https://cloud.githubusercontent.com/assets/5398977/23801055/4e7c1bc4-05b7-11e7-93ac-a35bd6ba59f9.png">

Also, If it helps, I uploaded the dSYM file successfully via a curl command from my terminal (and got OK in response).

Any help figuring out why I can't see the lines that caused the error in stack trace?

------

(If this bug is more fitted to the Bugsnag react native issues page, please tell me and I will post it there)

**Comment by kattrali** [comment]
Thanks for the report, @yaronlevi. Breaking things down below:

> These lines of code simply access an array's index which is out of range.
>
> The error is being reported to Bugsnag and I can see it in the dashboard but the stack trace has nothing to do with lines of code that causes the error or some kind of a hint to where I can find them. Instead, I get this error title:
>
> ```swift
> generic specialization <Swift.Int> of Swift._ContiguousArrayBuffer._checkValidSubscript (Swift.Int) -> ()
> ```

Well, I think there are two things going on here. The error description and top method line makes sense, because the array is called [at subscript `3` which is invalid](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Subscripts.html).  Though this should be identified as being a method in the Swift standard library and thus not the title of your error because it would be marked as not "in project". This usually indicates a dSYM has not being uploaded, or that some are missing.

> Also, If it helps, I uploaded the dSYM file successfully via a curl command from my terminal (and got OK in response).
>
> Any help figuring out why I can't see the lines that caused the error in stack trace?

It certainly looks like something needs fixed here, potentially that the uploaded dSYM doesn't match the build being run. Would you mind writing an email to  support@bugsnag.com with a link to the example error so we can look at your account more closely? 

As this is likely not something I can resolve with code changes, I'm going to close this issue, but feel free to reopen if more information arises.

**Comment by yaronlevi** [comment]
Ok I will try to generate the dSYM again, and if it problem wont resolve I'll send and email to support.

**Comment by yaronlevi** [comment]
Ok I made sure the the dSYM is updated but, again, I get the same error:

> EXC_BREAKPOINT
>     ReactModule.swift generic specialization <Swift.Int> of Swift._ContiguousArrayBuffer._checkValidSubscript (Swift.Int) -> ()
>     breakdown @objc breakdown.LocationService.startRecord (Swift.String) -> () with unmangled suffix "_merged"
>     Frameworks/CoreFoundation.framework/CoreFoundation ___invoking___
>     Frameworks/CoreFoundation.framework/CoreFoundation -[NSInvocation invoke]
>     Frameworks/CoreFoundation.framework/CoreFoundation -[NSInvocation invokeWithTarget:]
>     breakdown -[RCTModuleMethod invokeWithBridge:module:arguments:]
>     breakdown -[RCTBatchedBridge callNativeModule:method:params:]
>     breakdown __33-[RCTBatchedBridge handleBuffer:]_block_invoke.359
>     /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
>     /usr/lib/system/libdispatch.dylib __dispatch_queue_drain$VARIANT$mp
>     /usr/lib/system/libdispatch.dylib __dispatch_queue_invoke$VARIANT$mp
>     /usr/lib/system/libdispatch.dylib __dispatch_root_queue_drain
>     /usr/lib/system/libdispatch.dylib __dispatch_worker_thread3
>     /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread



As you can see, I can know in which method the error happned: "breakdown.LocationService.startRecord", which means it started in startRecord(). So this is good. But I do not know the specific line number. I am sending an email to support.
