### ISSUE TITLE
When resuming suspended threads, Bugsnag does not respect suspend_count

### ISSUE THREAD

**Issue by cwalo** [bugsnag/bugsnag-cocoa#1410]
### Describe the bug
In crash and app hang scenarios, Bugsnag suspends threads in order to capture stacktraces at the time events occur. I was perusing the Darwin documentation and noticed this detail for `thread_suspend`:

> To resume a suspended thread, use thread_resume. **If the suspend count is greater than one, thread_resume must be repeated that number of times**. [Link](https://web.mit.edu/darwin/src/modules/xnu/osfmk/man/thread_suspend.html)

The Bugsnag SDK [iterates over the suspended the threads and calls `thread_resume`](https://github.com/bugsnag/bugsnag-cocoa/blob/efd8dc7af9efb2d0e3748e6e2437a5081ca0b195/Bugsnag/KSCrash/Source/KSCrash/Recording/Tools/BSG_KSMach.c#L475), but it doesn't appear to respect the `suspend_count`. Should it? As is, can this result un-resumed threads? 

All said, I'm not sure if there's really an issue here, but It seems at least possible(?) that the system crash tooling could also suspend threads resulting in a `suspend_count` higher than 1.

### Steps to reproduce
N/A

### Environment
* Bugsnag version: 6.16.1
* CocoaPods version: N/A
* Carthage version (if any): N/A
* iOS/tvOS/macOS version(s): iOS 15.5
* Simulator or physical device: Either
* Xcode version: Xcode 13.4
* Swift version (if applicable): N/A

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by johnkiely1** [comment]
Hi @cwalo

As you correctly mentioned Bugsnag does suspend threads at the point of error capture. While the Darwin documentation does mention the possibility of the suspend count being greater than 1, when Bugsnag resumes the threads we are simply resuming the threads that we suspended. In other words we are undoing our increment.  This also means that any threads that may have already been suspended at the point Bugsnag calls `thread_suspend` would return to their previous state rather than Bugsnag incorrectly resuming them.
