### ISSUE TITLE
How accurate App Hangs are?

### ISSUE THREAD

**Issue by andre-alves** [bugsnag/bugsnag-cocoa#1424]
Bugsnag is reporting a lot of App Hangs for our app (more than any other type of crash) and although some places are indeed doing some kind of expensive operation (like IO operations or locking resources), it seems that many reports are "random" or flaky, and we never succeeded in reproducing them in-house.

This report, for example:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/7773955/177367822-ad5c0b0b-817f-404f-8d79-7a36032673df.png">

Is it really possible for iOS to hang and crash just for checking the protocol conformance of an object?

My understanding is that there is no clear signal that the app was terminated due to a hang, so Bugsag SDK has some heuristics to try to identify these terminations (similar to OOM crashes). How accurate these heuristics are? Is it possible to have false positives?

Thanks!

_----EDIT----_

_We are using Bugsnag version `6.16.4` and the app is for iOS only._

**Comment by yousif-bugsnag** [comment]
Hi @andre-alves,

For OOM detection, Bugsnag does use a heuristic to calculate whether the previous run of your application crashed due to an Out of Memory exception as Apple does not provide an event hook or signal when this occurs.

However App Hangs are detected by monitoring the main thread for responsiveness - if the main thread is busy or blocked and stops responding to messages on its queue for a given amount of time (2 seconds by default), this is detected as an App Hang. If an App Hang ends with termination by the system watchdog, this is reported as a fatal App Hang. This means that some of the crashes which previously would have been incorrectly reported as OOMs are now correctly reported as App Hangs. 

At the point the App Hang threshold is exceeded we snapshot the running threads and that's how we derive the stacktrace we report. So it's possible that some other expensive operation on the same code path is responsible for the majority of the unresponsiveness and it's just that this is what is executing at the top of the stack at the point the threshold is reached.

I hope that helps explain things! Let us know if you have any further questions on this.

**Comment by andre-alves** [comment]
Thanks @yousif-bugsnag, that clarified for me.
