### ISSUE TITLE
Setting User adds Custom json_data instead of updating User

### ISSUE THREAD

**Issue by emuye** [bugsnag/bugsnag-cocoa#144]
I'm setting the user in our code like this:
```Bugsnag.configuration()?.setUser(email, withName: profile.name, andEmail: profile.email)```

In Bugsnag the errors are still reported with UUID user id and the user data only appears in 
CUSTOM/json_data
```
{"nserror":{
  "domain":"Error Running JS: general.checkHeight('15b8206d0a457fcc');. Error Optional(Error Domain=WKErrorDomain Code=4 \"A JavaScript exception occurred\" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: general, WKJavaScriptExceptionSourceURL=file:\/\/\/var\/containers\/Bundle\/Application\/6CBE68A6-97EB-4E8E-B1DF-68E65A577C49\/Superhuman.app\/email.css, NSLocalizedDescription=A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber=8})",
  "reason":"",
  "code":-8481282699648894470},
  "user":{"id":"email","name":"","email":"email"}
}
```
```
USER/id 5e1107e874b251609b2083d8f6517fc03a641abc
```

Configuration:
Bugsnag 5.7.0, Xcode 8.3.1, iOS 10.3.1

**Comment by kattrali** [comment]
Thank you for the report, @emuye. It took testing a few edge cases, but I determined that this is a JSON parsing error within the underlying crash reporting library that we are using. Using the example error you provided, I can confirm that this is fixed in v5.8.0, in which I changed the version of the library we depend on. 🎉
