### ISSUE TITLE
Apple's update to their API policy about Privacy Manifest

### ISSUE THREAD

**Issue by ika020202** [bugsnag/bugsnag-cocoa#1589]
### Description
Apple has announced the[ Privacy Manifest ](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests), required by apps and SDKs.

**Describe the solution you'd like**
A solution exists, as shown in the official WWDC video.
https://developer.apple.com/videos/play/wwdc2023/10060/

However, CocoaPods does not seem to officially support this feature currently, so this feature needs to be discussed and investigated. 
I have built the Issue to make it known, as BugSnag handles a lot of Privacy information as defined by Apple.

**Describe alternatives you've considered**

**Additional context**
See: https://github.com/CocoaPods/CocoaPods/issues/10325
Ref: https://developer.apple.com/forums/thread/733537

**Comment by clr182** [comment]
Hi @ika020202 
Thank you for raising this issue. We are aware of the changes Apple are making that would require a Privacy Manifest/ approval reasons.

We do have some items on our backlog aimed at investigating this further, While I do not have a date for this release, we assure you we will have something in place to address this issue by the time Apple makes this change. In the meantime while we investigate this further, I have some approved reasons I can share which should be declared for why BugSnag is using some of these APis: 

`system_boot_time_apis: [mach_absolute_time]`
Approved reason:

> 35F9.1
Declare this reason to access the system boot time in order to measure the amount of time that has elapsed between events that occurred within the app or to perform calculations to enable timers.
Information accessed for this reason, or any derived information, may not be sent off-device. There is an exception for information about the amount of time that has elapsed between events that occurred within the app, which may be sent off-device.

`user_defaults_apis: [NSUserDefaults]`
Approved reason:

> CA92.1
Declare this reason to access user defaults to read and write information that is only accessible to the app itself.
This reason does not permit reading information that was written by other apps or the system, or writing information that can be accessed by other apps.

`file_timestamp_apis: [fstat]`
Approved reasons:

> DDA9.1
Declare this reason to display file timestamps to the person using the device.
Information accessed for this reason, or any derived information, may not be sent off-device.
C617.1
Declare this reason to access the timestamps of files inside the app container, app group container, or the app’s CloudKit container.
3B52.1
Declare this reason to access the timestamps of files or directories that the user specifically granted access to, such as using a document picker view controller.

`disk_space_apis: [statfs]`
Approved reasons:

> 85F4.1
Declare this reason to display disk space information to the person using the device. Disk space may be displayed in units of information (such as bytes) or units of time combined with a media type (such as minutes of HD video).
Information accessed for this reason, or any derived information, may not be sent off-device.
E174.1
Declare this reason to check whether there is sufficient disk space to write files, or to check whether the disk space is low so that the app can delete files when the disk space is low. The app must behave differently based on disk space in a way that is observable to users.
Information accessed for this reason, or any derived information, may not be sent off-device. There is an exception that allows the app to avoid downloading files from a server when disk space is insufficient.

**Comment by ika020202** [comment]
Thanks for replying and sharing the reason for the Required Reason API @clr182.

In addition to these Required Reason APIs, I think it is necessary to describe Privacy Nutrition Label Types.
Ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

**Comment by clr182** [comment]
Hi @ika020202 
Thank you for sharing these resources. We will let you know via this issue thread once we have a suitable update regarding this information.

**Comment by nabs-m** [comment]
Hey @clr182. The approved reasons for using disk space APIs mention that disk space info `may not be sent off-device`. I believe the current use violates that since available disk space is reported with each crash in Bugsnag. Any thoughts on how this is going to be handled?

**Comment by clr182** [comment]
Hi @nabs-m 
We intend on addressing this in our next release, ahead of Apples policy changes.
Our plan is to stop reporting the disk space in the short term and amend our Jailbreak detection algorithm to check for the presence of a system file in a way that doesn't use the prescribed system call. 

Once a release is out we will be sure to update this thread.

**Comment by mclack** [comment]
Hi all,

We can now confirm that Apple's new API usage rules have been addressed in v6.28.0 of `bugsnag-cocoa`: https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.28.0

This version:
- Removes `app.freeDisk` (except on macOS) as this is no longer allowed to be reported off device.
- Removes use of `stat` and `fstat` with equivalent, permitted checks. This does not impact any SDK functionality.
- A [Privacy Manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) covering BugSnag data and API usage.

Releases will be made to cross-platform SDKs in due course early in 2024 (i.e. for React Native, Unity, Unreal and Flutter SDKs).

More information on this can be found in our documentation: https://docs.bugsnag.com/platforms/ios/appstore-privacy/#declaring-required-reasons-for-api-usage
