### ISSUE TITLE
Installing via Carthage compiles only OSX.workspace

### ISSUE THREAD

**Issue by pwightman** [bugsnag/bugsnag-cocoa#161]
Hi!

When I add `github "bugsnag/bugsnag-cocoa"` to my Cartfile as instructed in the README and then run `carthage update`, I see this in the build output:

```
*** Building scheme "KSCrash" in Mac.xcworkspace
*** Building scheme "KSCrash-TVOS" in TVOS.xcworkspace
*** Building scheme "KSCrash-iOS" in iOS.xcworkspace
*** Building scheme "Bugsnag" in OSX.xcworkspace
*** Building scheme "Bugsnag" in OSX.xcworkspace
*** Building scheme "Bugsnag" in OSX.xcworkspace
```

The `KSCrash` dependencies for Mac/tvOS/iOS are built correctly, but the OSX workspace is built 3 times for `Bugsnag`. I can't find anything concrete about how Carthage handles projects with multiple root-level xcworkspace files, so it's hard to say what's "at fault" here (could very well be me). Any ideas?

**Comment by pwightman** [comment]
To be clear: I'm trying to use this in an iOS app, but only the `OSX.xcworkspace` is being built (and it's being built 3 times).

**Comment by kattrali** [comment]
Thanks for the report , @pwightman. That's incredibly odd. There was an issue in the past with the reverse, which is why the [macos guide](https://docs.bugsnag.com/platforms/macos/) specifies the Carthage build specify the platform:

```
carthage build --platform macos
```

Maybe try with `--platform ios`? If that works, we can update the docs to always specify a platform when building.

**Comment by pwightman** [comment]
Hey that worked! Thanks @kattrali!

**Comment by kattrali** [comment]
Awesome! I'll update the docs accordingly.
