### ISSUE TITLE
[Feature Request] Automatic tracking of out of memory crashes

### ISSUE THREAD

**Issue by benasher44** [bugsnag/bugsnag-cocoa#243]
Right now we rely on user reports of specific scenarios that lead to out of memory crashes, which isn’t ideal. It’d be great if this could be part of Bugsnag’s feature set, even if it meant it lived in beta as it were perfected. Facebook has a great post about how they determine that an app exit was from out of memory [here](https://code.facebook.com/posts/1146930688654547/reducing-fooms-in-the-facebook-ios-app/).

Thanks for your consideration!

**Comment by fractalwrench** [comment]
Thanks for suggestion @benasher44 - I think this would make a lot of sense and Facebook's blog post gives a very useful overview.

**Comment by thatjuan** [comment]
I have been working on a solution based on [Uber's StartupReasonReporter library](https://github.com/uber/startup-reason-reporter).

I have nothing to share yet, but I wanted to link it here as the BugSnag team might benefit from this. OOM detection would be a really useful feature to have.

**Comment by mividtim** [comment]
@thatjuan Have you made enough progress to share some code with the community? I would find it very useful. Thanks!

**Comment by jeffremer** [comment]
I'm planning on making use of Uber's StartupReasonReporter library to report whether or not the app had crashed on prior launch to our own internal analytics store (for use side-by-side with Bugsnag in crash analysis). We don't necessarily need this capability right in Bugsnag automatically, though that would be useful.

In order to determine if the app had crashed on last launch I simply exposed the property `crashedLastLaunch` property of `BSG_KSCrash (Advanced)` as a class property on `Bugsnag`. I'm wondering if it'd be worth it or OK to upstream that small addition to support use cases like ours?

**Comment by snmaynard** [comment]
We are actually working on this right now - we should have oom detection (and also as a side effect I believe we are cleaning up crash since last launch detection too.

**Comment by jeffremer** [comment]
> We are actually working on this right now - we should have oom detection (and also as a side effect I believe we are cleaning up crash since last launch detection too.

Awesome, thanks, great to hear. As a feature request I'd love to just have something like `Bugnsag.crashedLastLaunch` available since we still need a synchronous way to determine if the app crashed on last launch. The Bugsnag `BugsnagBeforeSendBlock` option doesn't quite cut it I think because it's only called if there was a crash. Since it is asynchronous and I'm not guaranteed to know when it would have been called I can't then report to our analytics the non-crashing startup reasons reliably.

**Comment by snmaynard** [comment]
I believe there will be a way to do this in the next version - stay tuned!

**Comment by kattrali** [comment]
Fixed in [v5.20.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v5.20.0)
