### ISSUE TITLE
onCrashHandler Swift Example

### ISSUE THREAD

**Issue by Jackhammer42** [bugsnag/bugsnag-cocoa#299]
Hey, I just have a question regarding the onCrashHandler. The documentation only provides a objective c example: https://docs.bugsnag.com/platforms/macos/configuration-options/#oncrashhandler

Is it possible to see an example in Swift?

**Comment by snmaynard** [comment]
You cant execute swift code from an async safe c context so it's not something we would document. Depending on what you want to do, you may do better with the before notify callback which runs when the app next starts before the report is actually sent. Take a look at that at https://docs.bugsnag.com/platforms/ios/configuration-options/#beforesendblocks.

I would recommend against trying to execute swift code from a crashing context as it could stop the report being sent at all and hard lock your app so that the user has to force kill it.

**Comment by Jackhammer42** [comment]
Ok, thank you very much for your reply. Maybe i try it the other way around and explain what i want to achieve ;-)

The goal is to use a `UIAlertController` to ask the user whether or not he wants to send a crash report, when the app restarted after a crash. 

I thought the onCrashHandler might be beneficial to that. Nevertheless I proceeded without it (actually quite similar to the way you suggests):

I used the beforeSendBlock in applicationDidFinishWithOptions to a) detect that a crash occurred and b) to save the report for later transmission.

```
let config = BugsnagConfiguration()
        
config.apiKey = "MY_API_KEY"
        
let block: BugsnagBeforeSendBlock = { (rawData, report) -> Bool in
        
CrashReportService.shared.globalReport = report
           
return false
            
}
  
config.add(beforeSend: block)

Bugsnag.start(with: config)
```

After my main view has loaded i check if `CrashReportService.shared.globalReport` is not nil. If so, i post a `UIAlertController` to ask the user if he wants to send the report. If the user accepts, i want to transmit the crash report to bugsnag.

My strongest candidate for this task is the `notify` method. But so far i did not manage to transmit the report. 

What do you think? Is that viable way to do this?

**Comment by fractalwrench** [comment]
@Jackhammer42 if you're asking for user consent, we'd typically recommend to show a `UIAlertController` once on the first launch of an application, and keep a record of whether the user approved/rejected crash reporting. For example, this could be persisted as a boolean in `NSUserDefaults`:

```
// call within UIAlertController positive button action
UserDefaults.standard.set(true, forKey: "CrashReportingEnabled")
```

You could then use a [`beforeSendBlock`](https://docs.bugsnag.com/platforms/ios/configuration-options/#beforesendblocks), which is called before each error report is sent. If you return false from this function, the report will be discarded and not sent to Bugsnag. Your callback would look something like this:

```
config.add { (rawData, report) -> Bool in
    // if user has not approved crash reporting, nothing will be sent
    return UserDefaults.standard.bool(forKey: "CrashReportingEnabled")
}
```

I'm going to close this issue off - please let us know if it doesn't fully address your problem and we'll be happy to reopen the ticket.

**Comment by Jackhammer42** [comment]
@fractalwrench yes, that would probably the easiest solution. Unfortunately, we decided against a general user consent question, in favour of a question after each crash. We want to use this approach, because we ask for a lot of confirmations at the first start of the app (Location, Notifications, Terms and Conditions etc.) and therefore we want to avoid an additional alert at this time in the session. We fear the user might denie the request out of pure annoyance.

Do you see a possibility to ask for consent after each crash?

**Comment by snmaynard** [comment]
I'll reopen so this doesnt get lost!

**Comment by fractalwrench** [comment]
@Jackhammer42 one possibility is that you could block the Bugsnag background thread until a user has consented. We've put together a gist of what this would look like [here](https://gist.github.com/kattrali/a88448fffc23dfefae7b4bb4bb183e36).

This example will ask for consent once per app launch, and would apply to all error reports sent to Bugsnag. One very important caveat is that this example relies on showing UI. Therefore any errors that happen between application launch and entering the foreground won't be recorded by Bugsnag.

Would this approach be closer in line with your requirements?

**Comment by fractalwrench** [comment]
@Jackhammer42 I believe you would be able to take a similar approach of blocking the background threads, and asking for user consent on the main thread. This comes with the same caveats that were listed for Cocoa and isn't something we'd generally recommend doing unless it's absolutely necessary for your requirements.

Here's a simplistic example which would work for crashes that occur on the background thread:

```
Bugsnag.beforeNotify {
    val latch = CountDownLatch(1)

    runOnUiThread {
        AlertDialog.Builder(this)
            .setTitle("Send report?")
            .setPositiveButton("ok", { dialog, _ ->
                latch.countDown()
            })
            .show()
    }

    latch.await() // CAUTION: will cause ANR if crash occurred on main thread
    true
}   
```

It's important to note that this example code will freeze your app if the crash occurs on the main thread, and cause an ANR. I believe that can be addressed by making the main thread do some useful work, rather than calling `latch.await`, which completely blocks the thread. You could have a look at `java.util.concurrent` and see if there's anything appropriate for this usecase, or attempt something simplistic like below:

```
boolean waitingOnUser = true;

while (waitingOnUser) {
    Thread.sleep(5);
    Log.d("App", "Still waiting on user");
}
```

I'll close this off for now as the Cocoa issue has been addressed. If you run into any further trouble, feel free to raise an issue in bugsnag-android or reach out to support@bugsnag.com.
