### ISSUE TITLE
Out of Memory errors are missing user ID

### ISSUE THREAD

**Issue by schukin** [bugsnag/bugsnag-cocoa#460]
### Description

When viewing OOM errors on the Bugsnag dashboard, none of them have the `userID` populated under the "User" tab. Our bug-fixing process often entails using the `userID` field to look up that device in our own internal logging system, or contacting that user directly, and in this case we're unable to do anything about these errors.

### Issue

The `userID` field is missing for OOM errors on the Bugsnag dashboard.

### Environment

Library versions:

* Bugsnag version: 5.23.0
* CocoaPods version: 1.7.1
* iOS/tvOS/macOS version: iOS 12.2 – 12.4 (we do not support iOS 13 yet, and have zero users on iOS 13. Enterprise software!)
* debug mode or production?: production
* How are you initializing Bugsnag? Can you share a snippet of your
  `AppDelegate` where Bugsnag is configured?

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        /// initialize bugsnag first thing, before doing anything else
        Bugsnag.start(withApiKey: "OUR_API_KEY")
        Bugsnag.configuration()?.setUser(uid, withName: nil, andEmail: nil)
        /// ... everything else ...
```

**Comment by xander-jones** [comment]
Hey @schukin, 

Out of memory errors are a little unusual in that they can't be caught and reported to Bugsnag directly. We cache device information ahead of time and if the app is terminated, we then determine after the fact that the app was likely terminated due to an out-of-memory condition and report the error at that point.

This means that we can't snapshot any information on device state at the point the out-of-memory condition occurs (you'll see that the Out Of Memory errors don't include fields such as `durationInForeground`, `batteryLevel`, `freeDisk`, `freeMemory`, `orientation`).

We are looking into what additional information could be captured which is not already being captured. I've requested that `userID` be considered for this, as it a pretty static data element.

**Comment by Theome** [comment]
I had exactly the same issue. The problem is that the crash reports are sent immediately when you call `Bugsnag`'s `start()` method, so your call to `setUser()` is too late. To fix this, initialize a configuration first and start `Bugsnag` providing the configuration:

    let configuration = BugsnagConfiguration(...)
    configuration.setUser(uid, withEmail: nil, andName: nil)
    Bugsnag.start(with: configuration)

This way, you'll get your custom user identifier associated with the crash reports. 

(I received this tip from Bugsnag support by email. Thanks!)

**Comment by xander-jones** [comment]
Good spot @Theome! I remember the very conversation. @schukin, as above, this will solve your issue if you have the user details upon launch. 🎉 

I am leaving this issue open as we are still considering enhanced metadata for OOM reporting.

**Comment by steve-nester-uk** [comment]
ROAD-880

**Comment by nickdowell** [comment]
Out Of Memory errors include user ID as of [v6.3.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.3.0) 🎉
