### ISSUE TITLE
Breadcrumbs are very expensive to log

### ISSUE THREAD

**Issue by dtorres** [bugsnag/bugsnag-cocoa#563]
Under the current implementation, Breadcrumbs can get very expensive.

During a profile of our app, I realised that leaving a breadcrumb was the most expensive stack in our app.
<img width="730" alt="Screenshot 2020-04-23 at 10 48 04" src="https://user-images.githubusercontent.com/71180/80078965-ea6acd80-854f-11ea-9f5a-4462582aac4d.png">

Notes:
- I did this profile on airplane mode, so my guess is, with internet the breadcrumb backlog gets cleared often so this doesn't become an issue in most testing.
- rewriting all breadcrumbs to a JSON file every time one is added can get expensive pretty quickly. Are there any considerations on using an append only approach?
- We happened to be calling this from the main thread, and blocking it to write that big JSON is a big red flag for any main thread bread crumbing.

Workaround:
- For now we will dispatch calls to add breadcrumbs to a background thread

/cc @rob-keepsafe

**Comment by rob-keepsafe** [comment]
Ideally this performance hit shouldn't be an implementation concern for clients and Bugsnag should process logging asynchronously in a more performant manner (while maintaining thread safety)

**Comment by mattdyoung** [comment]
Hi @dtorres @rob-keepsafe 

Whether or not you're in airplane mode won't impact this, breadcrumbs are only sent to Bugsnag as part of a subsequent error report so are always persisted to storage and not sent to Bugsnag until a handled error is reported or crash occurs.

The reason we persist these to storage rather than keep in memory is there can be forced terminations of the app such as out of memory conditions where the only way Bugsnag can report the breadcrumbs leading up to the OOM is if we've already persisted them.

There may be ways we can improve the performance of this though so I've raised this with the team who have a few ideas we could look at for a future release.

Adding the breadcrumbs on a background thread is an option but this would mean you get scenarios where the app gets terminated and some breadcrumbs are lost.

**Comment by sethfri** [comment]
Hi @mattdyoung, any update on this issue?

**Comment by mattdyoung** [comment]
@sethfri - we haven't determined the best approach for this yet, but we'll provide updates here when we're able to progress this issue.

**Comment by nickdowell** [comment]
We have just released [v6.2.3](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.2.3) that contains improvements to breadcrumbs performance.
