### ISSUE TITLE
Expose BSGOutOfMemoryErrorClass as public API

### ISSUE THREAD

**Issue by jparise** [bugsnag/bugsnag-cocoa#570]
### Description

OOM events use an internal `BSGOutOfMemoryErrorClass` exception name:

```objc
static NSString *const BSGOutOfMemoryErrorClass = @"Out Of Memory";
```

It's therefore not possible to match against these exceptions (in a "before send" block, for example) without making an assumption about the exception name.

**Describe the solution you'd like**

`BSGOutOfMemoryErrorClass` could become part of the public API if this symbol was made available through Bugsnag's header files.

**Describe alternatives you've considered**

At the moment, we can only assume that the exception name is—and will remain—the string literal `@"Out Of Memory"`.

**Comment by phillipsam** [comment]
@jparise Thanks for the suggestion, we will look into what we can do on this.

**Comment by steve-nester-uk** [comment]
After some discussion we feel this isn’t quite the right direction for the API design.  Moving this string to the public API could limit changes in future.  Per the discuss on PR [249](https://github.com/bugsnag/platforms-notifier-spec/pull/249) we are discussing a more general mechanism to check the type of event.  

Closing this issue for now, but the thread is still open should you have further questions/comments.

**Comment by bolsinga** [comment]
Hi @steve-nester-uk Is there a way in Bugsnag 6.x to determine if a crash is OOM before sending? Thank you.

**Comment by kstenerud** [comment]
We're currently in the process of revamping how OOM events are detected and reported in the Bugsnag client. It currently goes through a separate channel due to limitations in how OOMs can be detected (Apple offers no direct method for this), but we're working on a way to allow it to follow the same path as the rest so that it can be detected and handled in a custom manner just like the others.
