### ISSUE TITLE
Send user error to Bugsnag in debug freeze the app

### ISSUE THREAD

**Issue by zhaoze1991** [bugsnag/bugsnag-cocoa#639]
### Description
I am trying to send user error to Bugsnag in iOS, then I hit performance issue and Bugsnag freeze my app.

method from my swift code:
```
Bugsnag.notifyError(error)
```

### Issue
`bsg_kscrash_reportUserException` function took 15~40 seconds to accomplish in simulator.
I also tested in a iPhone 7 Plus device in debug, this function needs ~10 seconds.

As digged into the function, `bsg_kscrw_i_writeAllThreads` and `bsg_kscrw_i_writeBinaryImages` popped to my eye,
I added:
```
        Bugsnag.setThreadTracingEnabled(false)
        Bugsnag.setWriteBinaryImagesForUserReported(false)
```
to my code then I would not have the perf issue anymore. 

### Environment
Library versions:
* iOS/tvOS/macOS version(s):
  - v5.23.2
* debug mode or production?:
 - debug
* How are you initializing Bugsnag? Can you share a snippet of your
  `AppDelegate` where Bugsnag is configured?
```swift
func setupBugsnag() {
    let config = BugsnagConfiguration()
    config.apiKey = "xxx"
    config.releaseStage = functionToGetReleaseStage()
    Bugsnag.start(with: config)
}
```
### Example code snippet

```swift
import Bugsnag

func sendError(domain: String, code: int, message: String) {
    let error = NSError(
                domain: domain,
                code: code,
                userInfo: [
                    NSLocalizedDescriptionKey: message,
                ])
   // this function hit perf issue...
    Bugsnag.notifyError(error)
}

```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by mattdyoung** [comment]
Hi @zhaoze1991 

Bugsnag does suspend threads to safely capture stacktraces from every thread which may result in a momentary pause but we haven't observed anything taking the tens of seconds you describe.

Can you try one or other of:
```
Bugsnag.setThreadTracingEnabled(false)
```
or:
```
Bugsnag.setWriteBinaryImagesForUserReported(false)
```
on its own so we can identify which code path it is causing the delay in your scenario?

Do you see the same performance slow down when you build for release rather than debug?

It would also be helpful if you could contact support@bugsnag.com with links to the error reports in your Bugsnag dashboard that took this length of time to report so we can analyze the error reports and see if there is anything unusual about them.

**Comment by zhaoze1991** [comment]
Hi @mattdyoung thanks for your response.

I haven't seen the same issue in release mode and I did not figure out the difference between debug/release.

The major issue is caused by `threadTracking`.. when I paused execution in XCode, bugsnag is executing on https://github.com/bugsnag/bugsnag-cocoa/blob/master/Source/KSCrash/Source/KSCrash/Recording/Tools/BSG_KSDynamicLinker.c#L212

the value of `symtabCmd->nsyms` is ~2600000 and we may have around ~100 threads at runtime

**Comment by johnkiely1** [comment]
Closing this issue as it has been continued on a related support ticket.

For the benefit of other readers this occurred on XCode version 11.3.1 but does not appear to happen on XCode 11.4.x.
